version: '3.9'

services:
  # Shell Config
  shell:
    # Name des Containers
    container_name: shell

    # Hostname
    hostname: "${COMPOSE_PROJECT_NAME}-shell"

    # Build-File
    build:
      context: ./shell
      args:
        SHELL_USER_SSHKEY: ${SHELL_USER_SSHKEY}
        PHP_VERSION: ${PHP_VERSION}
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_USER: ${GIT_USER}
    
    # Verzeichnisse verknüpfen
    volumes:
      - ${PROJECT_VOLUME}:/var/projects

    # Portmapping
    ports:
      - "${SHELL_SSH_PORT}:22"


  # Nginx Config
  nginx:
    # Name des Containers
    container_name: nginx

    # Build-File
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    
    # Verzeichnisse verknüpfen
    volumes:
      # Projekte
      - ${PROJECT_VOLUME}:/var/projects
      # Configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d

    # php-fpm Container muss vorhanden sein
    depends_on:
      - php-fpm
        
    # Portmapping
    ports:
      - "${NGINX_PORT}:80"      
  
  # PHP-FPM Config
  php-fpm:
    # Name des Containers
    container_name: php-fpm

    # Build-File
    build:
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}

    # Verzeichnisse verknüpfen
    volumes:
      # Muss das gleiche Mapping sein wie bei nginx!
      - ${PROJECT_VOLUME}:/var/projects  

      
# Volumes definieren
volumes:
  private-volume:
    # Volume wird extern erstellt und nicht von Docker Compose
    external: true
                